# Generated by Django 3.2 on 2021-05-02 09:32

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210428_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, related_name='ratings', to='movies.movie', verbose_name='Фильм'),
        ),
    ]
